### ISSUE TITLE
Fix coveralls to use github actions

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/protocol#437]
Our current coveralls workflow using the npm module is deprecated instead `npm run coverage` will still generate the report but this now has to be uploaded to coveralls using a github action 

```
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
 ```
